apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-ml
  template:
    metadata:
      labels:
        app: fastapi-ml
    spec:
      containers:
        - name: fastapi
          image: ml_fastapi_docker
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
